# Generated by Django 4.2.27 on 2025-12-29 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_student_section'),
        ('timetable', '0001_initial'),
        ('academics', '0002_alter_batch_id_alter_section_department_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attend_session', to='academics.section')),
                ('time_table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attend_timetable', to='timetable.timetable')),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent')], max_length=30)),
                ('marked_at', models.DateTimeField(auto_now_add=True)),
                ('attendance_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_attended_session', to='attendanceapp.attendancesession')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_attendance', to='accounts.student')),
            ],
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.student')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holiday_section', to='academics.section')),
            ],
            options={
                'unique_together': {('section', 'date')},
            },
        ),
    ]
