from django.urls import path
from .views import (BatchCreateView, 
                    BatchListView, 
                    BatchUpdateView, 
                    SemesterCreateView, 
                    SemesterListView, 
                    SubjectCreateView, 
                    SubjectListView, 
                    SubjectUpdateView, 
                    SubjectMappingCreateView, 
                    SubjectMappingListView, 
                    SubjectMappingUpdateView, 
                    SectionCreationView, 
                    SectionListView, 
                    SectionUpdateView,
                    DashboardView)
from timetable.views import (PeriodCreateView,
                            PeriodUpdateView,
                            PeriodListView,
                            TimetableCreateView,
                            TimetableUpdateView,
                            TimetableListView)

urlpatterns = [
    path('dashboard/', DashboardView.as_view(), name='admin_dashboard'),
    path('batch/create/', BatchCreateView.as_view(), name='batch_create'),
    path('batch/list/', BatchListView.as_view(), name='batch_list'),
    path('batch/<int:pk>/update/', BatchUpdateView.as_view(), name='batch_update'),
    path('semester/create/', SemesterCreateView.as_view(), name='semester_create'),
    path('semester/list/', SemesterListView.as_view(), name='semester_list'),
    path('subject/create/', SubjectCreateView.as_view(), name='subject_create'),
    path('subject/list/', SubjectListView.as_view(), name='subject_list'),
    path('subject/<int:pk>/update/', SubjectUpdateView.as_view(), name='subject_update'),
    path('subject/semester/create/', SubjectMappingCreateView.as_view(), name='subject_semester_create'),
    path('subject/semester/list/', SubjectMappingListView.as_view(), name='subject_semester_list'),
    path('subject/semester/<int:pk>/update/', SubjectMappingUpdateView.as_view(), name='subject_semester_update'),
    path('section/create/', SectionCreationView.as_view(), name='section_create'),
    path('section/list/', SectionListView.as_view(), name='section_list'),
    path('section/<int:pk>/update/', SectionUpdateView.as_view(), name='section_update'),
    path('period/create/', PeriodCreateView.as_view(), name='period_create'),
    path('period/<int:pk>/update/', PeriodUpdateView.as_view(), name='period_update'),
    path('period/list/', PeriodListView.as_view(), name='period_list'),
    path('time-table/create/', TimetableCreateView.as_view(), name='timetable_create'),
    path('time-table/<int:pk>/update/', TimetableUpdateView.as_view(), name='timetable_update'),
    path('time-table/list/', TimetableListView.as_view(), name='timetable_list')
]
