# Generated by Django 4.2.27 on 2025-12-28 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_alter_batch_id_alter_section_department_name_and_more'),
        ('accounts', '0002_alter_student_id_alter_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_section', to='academics.section'),
        ),
    ]
